export const LIMITS = {
  anonymousPerDay: 3,
  anonymousPerDayPerIpBlock: 6,
  signedInPerMonth: 10,
  maxUrlLength: 2048,
  extractionTimeoutMs: 40_000,
  extractionMaxAttempts: 3,
  extractionRetryBackoffMs: 1_500,
  generationTimeoutMs: 150_000,
  maxScreenshotSizeMb: 5,
  maxOutputCharacters: 60_000,
  runLockWindowMs: 5 * 60_000,
  extractionWallClockMs: 100_000,
  screenshotUploadMs: 30_000,
  screenshotFullMs: 20_000,
  pipelineWallClockMs: 280_000,
  crawlPageTimeoutMs: 8_000,
  crawlFetchTimeoutMs: 6_000,
  crawlSitemapTimeoutMs: 5_000,
  cloudflareWaitMs: 12_000,
  pageSettleLoadMs: 8_000,
  pageSettleNetworkIdleMs: 3_500,
  pageSettleDelayMs: 3_000,
  pageStabilityMinWaitMs: 700,
  pageStabilityIntervalMs: 500,
  pageStabilityMaxWaitMs: 12_000,
  pageStabilityFrames: 2,
  pageStabilitySampleQuality: 30,
  pageScrollStepRatio: 0.8,
  pageScrollDelayMs: 200,
  pageScrollMaxSteps: 24,
  pageScrollSettleMs: 500,
  heroReadyMaxWaitMs: 5_000,
  heroReadyPollMs: 150,
  autoScrollWallMs: 10_000,
  scrollToTopSettleMs: 350,
  motionExtractionWallClockMs: 120_000,
  motionScrollStepRatio: 0.75,
  motionScrollMaxSteps: 40,
  motionScrollSettleMs: 150,
  motionScrollQuietMs: 220,
  motionScrollMaxMs: 14_000,
  deepScrollWallMs: 18_000,
  motionDomQuietMs: 320,
  motionDomQuietMaxWaitMs: 6_000,
  motionMaxMediaAssets: 60,
  motionMaxNetworkAssets: 120,
  crawlMaxPages: 10,
  crawlMaxDepth: 2,
  crawlConcurrency: 4,
  crawlTotalCharCap: 60_000,
  crawlPerPageCharCap: 8_000,
  crawlMinFetchContentChars: 500,
  partialSalvageMinChars: 2_000,
  minSkillBodyChars: 500,
  evaluationTimeoutMs: 20_000,
  metaGenerationTimeoutMs: 15_000,
} as const;

export const HERO_LOADER_SELECTORS = [
  '[class*="preloader" i]',
  '[id*="preloader" i]',
  '[class*="loader" i]',
  '[id*="loader" i]',
  '[class*="spinner" i]',
  '[id*="spinner" i]',
  '[class*="splash" i]',
  '[aria-busy="true"]',
] as const;

export const QUOTA_PERIOD = {
  anonymous: "day",
  signedIn: "month",
} as const;

export const RANKING = {
  bookmarkWeight: 5,
} as const;
