export const URL_PLACEHOLDERS = [
  "jumia.com.ng",
  "amazon.com",
  "linkedin.com/jobs",
  "indeed.com",
  "glassdoor.com",
  "booking.com",
  "airbnb.com",
  "konga.com",
  "paystack.com",
  "stripe.com",
  "github.com",
  "reddit.com",
  "news.ycombinator.com",
  "techcrunch.com",
  "producthunt.com",
  "crunchbase.com",
  "x.com",
  "instagram.com",
  "youtube.com",
  "medium.com",
  "notion.so",
  "linear.app",
  "vercel.com",
  "supabase.com",
  "docs.stripe.com",
  "nextjs.org",
  "tailwindcss.com",
] as const;

export const URL_PLACEHOLDER_INTERVAL_MS = 2400;